allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@inertiajs/core@3.6.0'
  - '@inertiajs/vite@3.6.0'
  - '@inertiajs/vue3@3.6.0'
