<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Services Prefix
    |--------------------------------------------------------------------------
    |
    | This value is the prefix used for Podman quadlet files. The default value
    | is the application name, which can be overruled when needed.
    |
    */

    'quadlet_prefix' => env('PODMAN_QUADLET_PREFIX', env('APP_NAME', 'laravel')),

    'proxy_prefix' => env('PODMAN_PROXY_PREFIX', 'proxy'),

    /*
    |--------------------------------------------------------------------------
    | Stubs Path
    |--------------------------------------------------------------------------
    |
    | This value is the path where preset folders (each containing a
    | "quadlets/" directory of ".quadlets" files and a "runtimes/" directory
    | of container build files) are looked up before falling back to the
    | vendor-provided ones. The fallback happens per preset, not as a whole
    | directory swap — customizing one preset (e.g. "containers/stubs/proxy")
    | doesn't require copying every other preset too.
    |
    */

    'stubs_path' => env('PODMAN_STUBS_PATH', 'containers/stubs'),

    /*
    |--------------------------------------------------------------------------
    | Working Path
    |--------------------------------------------------------------------------
    |
    | The host path baked into the "{{workingPath}}"/"{{runtimePath}}"
    | placeholders. It does not affect where Artisan itself reads or writes
    | files — that's always base_path(). Defaults to base_path(); override
    | when rendering happens somewhere whose filesystem view of the project
    | isn't the host's, e.g. inside the container used by "Setting up
    | without PHP on the host".
    |
    */

    'working_path' => env('PODMAN_WORKING_PATH'),

    /*
    |--------------------------------------------------------------------------
    | Service UID and GID
    |--------------------------------------------------------------------------
    |
    | These values determine the UID and GID used for Podman quadlet files.
    | The default values are null, which means the system's UID and GID
    | will be used. These can be overruled when needed.
    |
    */

    'quadlet_uid' => env('PODMAN_QUADLET_UID'),

    'quadlet_gid' => env('PODMAN_QUADLET_GID'),

    /*
    |--------------------------------------------------------------------------
    | Publish Path
    |--------------------------------------------------------------------------
    |
    | This value is the path where "podman:generate" writes every rendered
    | preset — its ".quadlets" files directly under "{publish_path}/{preset}"
    | and its runtime build files under "{publish_path}/{preset}/runtimes".
    | Install the rendered files with "lpod install {preset}/{service}"
    | (see "Setting up without PHP on the host").
    |
    */

    'publish_path' => env('PODMAN_PUBLISH_PATH', 'podman'),

    /*
    |--------------------------------------------------------------------------
    | SELinux Volume Mapping
    |--------------------------------------------------------------------------
    |
    | This value determines whether the Z, z and U SELinux volume flags are
    | kept on Volume= entries. Disable this on hosts that do not run SELinux,
    | since these flags are rejected there.
    |
    */

    'selinux_volume_mapping' => env('PODMAN_SELINUX_VOLUME_MAPPING', true),

    /*
    |--------------------------------------------------------------------------
    | Reload Systemd
    |--------------------------------------------------------------------------
    |
    | This value determines whether to reload systemd after installing a quadlet.
    | The default value is true, which means that systemd will be reloaded after installation.
    |
    */

    'reload_systemd' => env('PODMAN_RELOAD_SYSTEMD', true),

    /*
    |--------------------------------------------------------------------------
    | Presets
    |--------------------------------------------------------------------------
    |
    | This value lists the presets published and generated by the
    | "podman:setup" command when no explicit preset is given. Any preset not
    | listed here can still be published/generated manually. Accepts either a
    | comma-separated string (handy for the PODMAN_DEFAULT_PRESETS env
    | variable) or a plain array of preset names.
    |
    */

    'presets' => env('PODMAN_DEFAULT_PRESETS', [
        'frankenphp-octane',
        'proxy',
    ]),

    /*
    |--------------------------------------------------------------------------
    | S3 Buckets
    |--------------------------------------------------------------------------
    |
    | These values list the S3 buckets created by the "podman:s3-setup" command,
    | and which of them should receive the CORS policy published with the "s3"
    | preset (see "podman:publish s3"). Accepts either a comma-separated string
    | (handy for the PODMAN_S3_BUCKETS / PODMAN_S3_CORS_BUCKETS env variables)
    | or a plain array of bucket names.
    |
    */

    's3_buckets' => env('PODMAN_S3_BUCKETS', [
        'local',
        'conversions',
        'segments',
        'secrets',
    ]),

    's3_cors_buckets' => env('PODMAN_S3_CORS_BUCKETS', [
        'conversions',
        'segments',
        'secrets',
    ]),
];
