import type {ReactNode} from 'react';
import clsx from 'clsx';
import Heading from '@theme/Heading';
import styles from './styles.module.css';

type FeatureItem = {
  title: string;
  description: ReactNode;
};

const FeatureList: FeatureItem[] = [
  {
    title: 'Adaptive streaming',
    description: (
      <>
        DASH and HLS playlists generated by Shaka Packager and Streamer, with
        multiple renditions, bitrates, and optional stream encryption.
      </>
    ),
  },
  {
    title: 'Modern Laravel stack',
    description: (
      <>
        Built on Laravel Octane with an Inertia and Vue frontend, PostgreSQL,
        and Typesense-powered search.
      </>
    ),
  },
  {
    title: 'Container-ready deployment',
    description: (
      <>
        Ships as Podman Quadlet units for systemd-managed hosts, with a
        best-effort Docker Compose setup as an alternative.
      </>
    ),
  },
];

function Feature({title, description}: FeatureItem) {
  return (
    <div className={clsx('col col--4')}>
      <div className="text--center padding-horiz--md">
        <Heading as="h3">{title}</Heading>
        <p>{description}</p>
      </div>
    </div>
  );
}

export default function HomepageFeatures(): ReactNode {
  return (
    <section className={styles.features}>
      <div className="container">
        <div className="row">
          {FeatureList.map((props, idx) => (
            <Feature key={idx} {...props} />
          ))}
        </div>
      </div>
    </section>
  );
}
