# https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/

replication_factor = 1 # Consider replication for production
consistency_mode = "consistent"

metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
metadata_snapshots_dir = "/var/lib/garage/snapshots"
metadata_fsync = true
data_fsync = false
disable_scrub = false
use_local_tz = false
metadata_auto_snapshot_interval = "6h"

db_engine = "lmdb"

block_size = "1M"
block_ram_buffer_max = "1GiB" # Consider 1-2GiB for heavy load
block_max_concurrent_reads = 48 # Boost to 64-128 for concurrent requests
block_max_concurrent_writes_per_request = 20 # Set to 32-64 for heavy load

lmdb_map_size = "1T"

compression_level = "none" # Data is mostly compressed, set to 1 if you also store uncompressed files

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "GENERATE ME... (openssl rand -hex 32)"

allow_world_readable_secrets = false
allow_punycode = false

[s3_api]
api_bind_addr = "[::]:3900"
s3_region = "garage"
root_domain = ".s3.stry.test"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.stry.test"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "GENERATE ME... (openssl rand -base64 32)"
metrics_token = "GENERATE ME... (openssl rand -base64 32)"
metrics_require_token = true
